### ISSUE TITLE
Feature Request: Quotation marks to delimit different filter fields in List view

### ISSUE THREAD

**Issue by michaelgfalk** [tomitrescak/mpce#10]
At the moment, in a list view that is filtered on multiple columns, a space is used to delimit each field the user can filter by.

This causes problems when searching string columns that can contain multiple words, such as the title of a book or the name of a person:

![image](https://user-images.githubusercontent.com/35712723/60487601-4d4e5800-9ce3-11e9-9120-fbb195139c96.png)

If the above list view had filters on title, date and place, then I could only search using one word of the title.

Would it be possible to use double quotations to enclose different sections of the search string, such that `"grand cyrus" 1777 Paris` or `"grand cyrus" "1777" "Paris"` would pull up all books with "grand" and "cyrus" in the title, published in 1777 in Paris?

**Comment by tomitrescak** [comment]
Implemented. Test and reopen when necessary.
