### ISSUE TITLE
Bug: When you delete a control from the `View Template` of a `List View`, elements to the right move left

### ISSUE THREAD

**Issue by michaelgfalk** [tomitrescak/mpce#13]
When I am editing the `View Template` of a `List View`, the controls can shift around. For example, let's say I wish to delete the `Lookup` from this view:
<img width="614" alt="Screen Shot 2019-07-05 at 9 02 52 am" src="https://user-images.githubusercontent.com/35712723/60689718-b90f0b80-9f03-11e9-9999-c8599348eaf8.png">
When I do, the `Link` element on column `Cerl ID` moves to the left:
<img width="614" alt="Screen Shot 2019-07-05 at 9 03 46 am" src="https://user-images.githubusercontent.com/35712723/60689737-e1970580-9f03-11e9-8d95-b4a1788e157d.png">

**Comment by tomitrescak** [comment]
Fixed
