### ISSUE TITLE
Feature Request: Subforms in Detail View

### ISSUE THREAD

**Issue by michaelgfalk** [tomitrescak/mpce#14]
Hi Tomas,

Perhaps this feature is already present... It would be nice to be able to embed subforms in the Detail view. For instance, if a book has multiple authors, it would be good to be able to display a table of the authors at the bottom of the screen. Or if there were multiple buyers at a particular auction, it would be nice to display all their names.

Cheers

**Comment by tomitrescak** [comment]
Yes, this is already possible, yet I need more precise example with exact views / database fields. Once I have that, I can record an instruction video for you.

The general idea here though is to use "ApolloQuery" component. This component can query the database for data and display them in any way you like.

**Comment by michaelgfalk** [comment]
Oh fantastic!!

To start with, could we try embedding a table into the `Work` Detail View that displays all of the `keywords` that have been assigned to it? The keywords are listed in the `keyword` table, and the `work_keyword` table lists which `keywords` have been assigned to which `works`.

**Comment by tomitrescak** [comment]
Michael

This view would be read only, would that still be ok?

Kind Regards

Dr. Tomas Trescak
Senior Lecturer In Intelligent Systems
School of Computing, Engineering and Mathematics
Western Sydney University | Locked Bag 1797 Penrith NSW 2751
P: 02 9852 9082 | M: 0487 261 213
E: t.trescak@westernsydney.edu.au
We acknowledge and respect Traditional Owners of the Lands, the Darug, Gundungurra, D’harawal, Wiradjuri and Bundjalung Peoples, upon which our campuses now stand. We continue to value the generations of knowledge Aboriginal and Torres Strait Islander Peoples embed within our University.

**Comment by michaelgfalk** [comment]
Yes, totally fine!

*Michael Falk*
*Postdoctoral Research Fellow* | Waves of Words: Mapping and Modelling
Australia's Pacific Past
<https://www.westernsydney.edu.au/dhrg/digital_humanities/featured/waves_of_words>
*Developer and Research Project Manager *| Digital Humanities Research Group
<https://www.westernsydney.edu.au/dhrg/digital_humanities>
School of Humanities and Communication Arts
Western Sydney University


Living and Writing in the Blue Mountains
https://www.michaelfalk.com.au

**Comment by michaelgfalk** [comment]
Hi Tomas,

I've had a look now at how this feature works and it's fantastic. Being able to write custom SQL is perfect. I also love the way you can customise the view of the subform. I've been able to add link elements to the table, which seem to work well.

Looking good!
