### ISSUE TITLE
Feature Request: Allow custom formats in string interpolations

### ISSUE THREAD

**Issue by michaelgfalk** [tomitrescak/mpce#15]
It is really useful to be able to use string interpolation when defining a lookup. Thank you for that.

It would be great, though, if it were possible to specify the format of the interpolated strings, e.g., only return the first ten characters of a datetime, so that only the date appears:

`Date:${date_column:10s}`

Or allow rounding of decimal columns

`Latitude:${latitude_column:2f}`

**Comment by tomitrescak** [comment]
Michael, this is already possible. Whatever goes between the curly brackets can contain javascript. Thus you can write things such as following:

```
Latitude: ${Math.round(latitude_column)}
```

or

```
Date: ${date_column.substring(0, 10)}
```
