### ISSUE TITLE
Bug: Link Element, 'New Window' target does not work on some machines

### ISSUE THREAD

**Issue by michaelgfalk** [tomitrescak/mpce#18]
On my machine, the 'New Window' target works correctly when a link is clicked.

However, on another user's machine, running the same version of Windows and of Chrome, it does not.

Could the problem be that the system adds `target=__empty` rather than `target=__blank` to the anchor element?

**Comment by tomitrescak** [comment]
Yes, the __blank option was incorrect. Should be fixed now.
