### ISSUE TITLE
Feature request: Add 'confirm' popup to delete buttons in the admin system

### ISSUE THREAD

**Issue by michaelgfalk** [tomitrescak/mpce#2]
The delete buttons in the admin tool are very powerful: in one click you can delete an entire view that may have taken hours to configure.

It would be good if the delete buttons had a pop-up asking the user to confirm their decision.

**Comment by tomitrescak** [comment]
I added the modal dialog that confirms this action. Moreover, you have undo and redo buttons in the top menu. So when you do anything silly you can always undo.
