### ISSUE TITLE
Bug: Search bar doesn't clear when you leave a list view

### ISSUE THREAD

**Issue by michaelgfalk** [tomitrescak/mpce#24]
When you go from one list view to another, the search terms in the search bar remain the same. So for instance, I type this in to my 'Confiscation' view...
<img width="440" alt="Screen Shot 2019-07-12 at 1 25 02 pm" src="https://user-images.githubusercontent.com/35712723/61100193-9737fa80-a4a8-11e9-968e-9df09a167f57.png">
Then when I go to my 'Agent' list view...
<img width="440" alt="Screen Shot 2019-07-12 at 1 26 21 pm" src="https://user-images.githubusercontent.com/35712723/61100224-ae76e800-a4a8-11e9-8893-15f1b8fc5cc5.png">
Could the search bar please clear when you go to a different list view?

**Comment by tomitrescak** [comment]
Fixed
