### ISSUE TITLE
Bug: Checkbox still doesn't work for boolean columns in the list view

### ISSUE THREAD

**Issue by michaelgfalk** [tomitrescak/mpce#25]
The checkbox throws and error in the List View. Here is the configuration...
<img width="767" alt="Screen Shot 2019-07-12 at 2 39 26 pm" src="https://user-images.githubusercontent.com/35712723/61102838-f26eea80-a4b2-11e9-84dd-088ef67625e0.png">
And here is the view...
<img width="839" alt="Screen Shot 2019-07-12 at 2 40 44 pm" src="https://user-images.githubusercontent.com/35712723/61102866-0d415f00-a4b3-11e9-810d-42f07c602032.png">

**Comment by tomitrescak** [comment]
Does it work in the real view though?

**Comment by tomitrescak** [comment]
Fixed

![image](https://user-images.githubusercontent.com/2682705/62283709-75e87f80-b452-11e9-92cf-0e16e0fb8ef6.png)

**Comment by michaelgfalk** [comment]
Perfect, thank you!
