### ISSUE TITLE
Bug: Cannot fix schema of table when it becomes invalid

### ISSUE THREAD

**Issue by michaelgfalk** [tomitrescak/mpce#26]
I made a field 'required' in my `edition` table, and then it broke the schema. The following error appears:
<img width="839" alt="Screen Shot 2019-07-12 at 2 40 44 pm" src="https://user-images.githubusercontent.com/35712723/61105304-ce180b80-a4bc-11e9-97b1-a4d59416dcb6.png">
I can't see any way of fixing the schema!

**Comment by tomitrescak** [comment]
I cant reproduce ;(( C you give me eps please? Thanks!

**Comment by michaelgfalk** [comment]
I can't remember how I did this either.
