### ISSUE TITLE
Bug: Dates being converted by timezone

### ISSUE THREAD

**Issue by michaelgfalk** [tomitrescak/mpce#27]
Hi Tomas,

Dates are being converted into a different timezone whenever they are retrieved from the database. This creates confusion for the user, who for instance will enter the date '1777-01-02' as the 'Date de Decision' for a 'Confiscation', but then will see the date '1777-01-01' displayed when they re-open the record. Looking in the underlying database, it appears that the correct value has been stored, so the problem must be with how dates are processed by the interface.

Cheers

**Comment by tomitrescak** [comment]
This is a tricky one. I'll check it out.

**Comment by tomitrescak** [comment]
Solved. The problem was due to converting to timezone.
Each date view field now contains the flag "local". If you specify this, the field will be converted to the local time zone. For you, it is best to leave this field as it is.

**Comment by tomitrescak** [comment]
Will deploy to staging later on.
