### ISSUE TITLE
Bug: Lookup fetching incorrect data

### ISSUE THREAD

**Issue by michaelgfalk** [tomitrescak/mpce#28]
In the list view, the correct data for this 'confiscation' is displayed. It is part of consignment 5.
![image](https://user-images.githubusercontent.com/35712723/61598486-f09ae900-ac61-11e9-821b-79cacc68f99b.png)
But when I click through to the detail view, the lookup field returns data for consignment **54**, rather than consignment **5**.
![image](https://user-images.githubusercontent.com/35712723/61598469-ccd7a300-ac61-11e9-8040-1e414cfd2ec1.png)

**Comment by michaelgfalk** [comment]
It seems to be a general problem with lookups that rely on integer values. There is the same issue with the 'judgement' field in the 'confiscations' table. The list view shows the correct judgment of 'condamne au pilon' for confiscation 6:
![image](https://user-images.githubusercontent.com/35712723/61604189-d70a9900-ac83-11e9-8bf8-0e6afc3f5323.png)
But in the Detail View, the incorrect judgment is displayed:
![image](https://user-images.githubusercontent.com/35712723/61604210-f73a5800-ac83-11e9-8e36-7f183fd87527.png)
'Condamne au pilon' has ID '1' in the 'judgment' table, while 'Une autre' has ID '13'. It appears that when the lookup tries to retrieve the data for judgment '1', it looks digit-by-digit, and ranks '13' as a closer match.

**Comment by tomitrescak** [comment]
Oh I know why this is happening .... yes, I'll look into it.

**Comment by tomitrescak** [comment]
Fixed
