### ISSUE TITLE
Bug: Empty date values displayed oddly

### ISSUE THREAD

**Issue by michaelgfalk** [tomitrescak/mpce#29]
In the detail view, a date is correctly displayed as unknown:
![image](https://user-images.githubusercontent.com/35712723/61598512-440d3700-ac62-11e9-8ab6-0dc6d2edc503.png)
But in the list view, the date is returned with a dummy value from 1899:
![image](https://user-images.githubusercontent.com/35712723/61598516-5ab38e00-ac62-11e9-9822-bb3e2c64e018.png)
No default is specified for the date in the 'View Template':
![image](https://user-images.githubusercontent.com/35712723/61598523-761e9900-ac62-11e9-9cca-eefc3e4b166b.png)

**Comment by tomitrescak** [comment]
This is fixed as dates are now transmitted in the string format to avoid any further issues
