### ISSUE TITLE
Feature request: link element opens in new tab/window

### ISSUE THREAD

**Issue by michaelgfalk** [tomitrescak/mpce#3]
The link element in the Detail view is very useful, but it would be improved if an additional option were added for 'open in new tab'. My suggestion would be that a checkbox could be added to the following section of the control's properties:

![image](https://user-images.githubusercontent.com/35712723/60473579-ffb8f780-9cb0-11e9-9a0e-0382fb0bb885.png)

**Comment by tomitrescak** [comment]
Implemented
