### ISSUE TITLE
Bug: Can't click on lookup element before it is bound

### ISSUE THREAD

**Issue by michaelgfalk** [tomitrescak/mpce#33]
A minor bug. When you create a new lookup control, it is not possible to click on it in the GUI until it is bound:
![image](https://user-images.githubusercontent.com/35712723/62014442-6663ff00-b1e4-11e9-8c87-63102e2c0b5c.png)
Of course, you can select it in the sidebar, but it would be nice to be able to click on it directly.

**Comment by tomitrescak** [comment]
This should be fixed
