### ISSUE TITLE
Bug: Boolean Values still not displaying in List View

### ISSUE THREAD

**Issue by michaelgfalk** [tomitrescak/mpce#35]
Hi Tomas,

There still seems to be a problem in `List View`. By default, boolean columns simply display no values. In this example, all the records should be displaying 'true', as they do correctly in `Detail View`:
<img width="698" alt="Screen Shot 2019-07-05 at 8 55 02 am" src="https://user-images.githubusercontent.com/35712723/60689629-c2e43f00-9f02-11e9-8e1f-3e6112a1cd5c.png">

I tried using the `View Template` to display a `checkbox` in the column:
<img width="698" alt="Screen Shot 2019-07-05 at 8 52 38 am" src="https://user-images.githubusercontent.com/35712723/60689635-db545980-9f02-11e9-9482-82ab1c0fc30f.png">

I tried using an `If` element as well, but perhaps I didn't configure it correctly:
<img width="698" alt="Screen Shot 2019-07-05 at 8 54 28 am" src="https://user-images.githubusercontent.com/35712723/60689639-e3ac9480-9f02-11e9-92d6-2b79d5966556.png">

_Originally posted by @michaelgfalk in https://github.com/tomitrescak/mpce/issues/7#issuecomment-508587685_

**Comment by tomitrescak** [comment]
The problem is that true / false values do not render as text, they are ignored.

Michael, the easiest solution here is to use a simple Text field. In the 'text' property you can use following expression to render 'yes' or 'no' based on the corporate entity.

```
${corporate_entity ? 'yes' : 'no' }
```
