### ISSUE TITLE
Feature Request: Allow view-only access to users without a login

### ISSUE THREAD

**Issue by michaelgfalk** [tomitrescak/mpce#36]
Could we please allow anyone without a login to view the list and detail views, without the possibility of changing any data?

**Comment by tomitrescak** [comment]
Hi, I got this implemented. It was quite complex task in the end as this required a dual view of the interface, where non-logged in users or users who have no "editor" or "admin" role cannot edit fields.

This is how the interface will look like now in the "readOnly" mode:

<img width="1333" alt="image" src="https://user-images.githubusercontent.com/2682705/62791814-39f68f80-bace-11e9-85a6-5fb3b58c6114.png">

**Comment by michaelgfalk** [comment]
This is awesome, thank you Tomas.

*Michael Falk*
*Postdoctoral Research Fellow* | Waves of Words: Mapping and Modelling
Australia's Pacific Past
<https://www.westernsydney.edu.au/dhrg/digital_humanities/featured/waves_of_words>
*Developer and Research Project Manager *| Digital Humanities Research Group
<https://www.westernsydney.edu.au/dhrg/digital_humanities>
School of Humanities and Communication Arts
Western Sydney University


Living and Writing in the Blue Mountains
https://www.michaelfalk.com.au
