### ISSUE TITLE
Bug: Masked input control has problems when editing existing data

### ISSUE THREAD

**Issue by michaelgfalk** [tomitrescak/mpce#38]
The `masked input` control works perfectly to validate a date input when a new record is created, but it causes problems when the user has to edit an existing record. The input appears to load the date correctly, but then returns an error message if the user tries to save:
![Screen Shot 2019-07-31 at 1 01 15 pm](https://user-images.githubusercontent.com/35712723/62180769-863a2500-b394-11e9-8185-1c21d1300bdf.png)
Incidentally, the `masked input` appears to have the same issue with timezones that the `date` control previously had. The date in the above example should be '1771-01-17'.

**Comment by tomitrescak** [comment]
I fixed this. Also, now I'm transfering dates from server in "string" mode, so there is not need to use "Date" formatter field as dates inherently come the same way they are in the database.

You will run into issues though, as you have some advanced checks for your dates and the system will NOT allow you to save a date such as '0000-00-00' or '1700-00-00'.

Please check following: https://stackoverflow.com/questions/44304777/er-truncated-wrong-value-incorrect-datetime-value

**Comment by michaelgfalk** [comment]
Thanks Tomas,

Does this mean that incomplete dates are no longer allowed?
![image](https://user-images.githubusercontent.com/35712723/62431663-95421e00-b76c-11e9-998d-e99e84c0304e.png)
