### ISSUE TITLE
Bug: Lookups not working when Value Field is numeric

### ISSUE THREAD

**Issue by michaelgfalk** [tomitrescak/mpce#4]
The Detaillink element is not linking to the detail view correctly. The following error appears:
![image](https://user-images.githubusercontent.com/35712723/60474645-86bc9e80-9cb6-11e9-998f-1cde0009a678.png)

**Comment by michaelgfalk** [comment]
It seems to be the same problem with lookups too:
![image](https://user-images.githubusercontent.com/35712723/60481245-e96e6400-9ccf-11e9-8f7d-d84c0ab7781c.png)
![image](https://user-images.githubusercontent.com/35712723/60481234-e2dfec80-9ccf-11e9-89e6-18dfdcc74ee4.png)
The DetailLink on 'ID' returns the 'no matching type for union' error, and as these images show, the lookup on the 'units' column is failing to return anything.

Both these features work perfectly well when the primary keys involved are strings.

**Comment by michaelgfalk** [comment]
I found the problem with the DetailLink: I had the wrong data type defined in the Table. But even after correcting this, and telling the system correctly which columns were numeric, the lookup continues to fail.

**Comment by michaelgfalk** [comment]
Fixing the data types in the table enabled the DetailLink to work. However, when a record is opened in Detail view, the lookups fail to load:
![image](https://user-images.githubusercontent.com/35712723/60483419-b086bd00-9cd8-11e9-9c85-4a0bf75da047.png)
This occurs even when the lookup worked correctly when the record was created.

This problem does not apply to lookups with string lookup values:
![image](https://user-images.githubusercontent.com/35712723/60483462-dca23e00-9cd8-11e9-833d-146b3851811f.png)

**Comment by michaelgfalk** [comment]
There is a type error:
![image](https://user-images.githubusercontent.com/35712723/60483696-f001d900-9cd9-11e9-9d54-2d7d506db0b1.png)

**Comment by tomitrescak** [comment]
Fixed
