### ISSUE TITLE
Feature request: Support for multi-column primary keys

### ISSUE THREAD

**Issue by michaelgfalk** [tomitrescak/mpce#6]
At current, the 'tables' tool only supports a single-column primary key:
![image](https://user-images.githubusercontent.com/35712723/60481726-fab87000-9cd1-11e9-8a5a-db942d7c8bb5.png)
Would it be possible to add support for multi-column primary keys?

**Comment by tomitrescak** [comment]
Can you elaborate on where you need this and what is the use?

**Comment by michaelgfalk** [comment]
Hi Tomas, could you take a look at the 'Authorship' view in our configured system? It has a three-column primary key, and I get the following error when I try to open the list view:
<img width="596" alt="Screen Shot 2019-07-04 at 4 36 57 pm" src="https://user-images.githubusercontent.com/35712723/60644633-09418b80-9e7a-11e9-939f-9a0af4a6f18e.png">

**Comment by michaelgfalk** [comment]
The underlying table has a multi-column primary key because it creates a many-to-many join.

`edition_author` records which person in the `agent` table wrote which edition in the `edition` table. Each `edition` could have multiple authors, and each person can play different roles on the book. For example, Joe Bloggs might be the 'primary' author, and Mary Stuart might be the 'editor'. In theory, one person could play more than one role. Perhaps Margaret Cavendish is the 'editor' of a book of essays, but also wrote one of the essays, so is also a 'secondary' author.

For this reason, there is a three-column key, on `edition_code` (foreign key to `edition_code.edition`, `author` (foreign key to `agent.agent_code`) and `author_type` (foreign key to `author_type.ID`).

If this will be a problem, I can change the database schema so that all tables like `edition_author` have a seperate `ID` column, and use a multi-column unique index to ensure that no duplicates are entered.

How would your system behave if an INSERT operation fails due to a duplicate key? Does it do an INSERT IGNORE or and INSERT UPDATE or would it simply fail to complete the insert?

**Comment by tomitrescak** [comment]
Michael

it would be great if you could setup a single primary key, e.g. autoincrement int column.
The multi primary keys are an issue and they do not bring much into the security landscape.
You can still setup for them to be unique keys.

It would be really difficult to setup multi keys.

Kind Regards

Dr. Tomas Trescak
Senior Lecturer In Intelligent Systems
School of Computing, Engineering and Mathematics
Western Sydney University | Locked Bag 1797 Penrith NSW 2751
P: 02 9852 9082 | M: 0487 261 213
E: t.trescak@westernsydney.edu.au
We acknowledge and respect Traditional Owners of the Lands, the Darug, Gundungurra, D’harawal, Wiradjuri and Bundjalung Peoples, upon which our campuses now stand. We continue to value the generations of knowledge Aboriginal and Torres Strait Islander Peoples embed within our University.

**Comment by michaelgfalk** [comment]
No problem. Will do!

**Comment by michaelgfalk** [comment]
I have changed the structure of our database. Thanks for your advice Tomas.
