### ISSUE TITLE
Bug: Display of Boolean values

### ISSUE THREAD

**Issue by michaelgfalk** [tomitrescak/mpce#7]
At the moment, boolean values do not seem to display correctly in a view:
![image](https://user-images.githubusercontent.com/35712723/60481782-4539ec80-9cd2-11e9-8444-27597850cafb.png)
Whether True or False, the value displayed is simply '[object]'

**Comment by michaelgfalk** [comment]
The boolean column also seems to break the DetailLink:
![image](https://user-images.githubusercontent.com/35712723/60481829-7f0af300-9cd2-11e9-92c5-451a244aed01.png)

**Comment by tomitrescak** [comment]
Fixed

**Comment by michaelgfalk** [comment]
Hi Tomas,

There still seems to be a problem in `List View`. By default, boolean columns simply display no values. In this example, all the records should be displaying 'true', as they do correctly in `Detail View`:
<img width="698" alt="Screen Shot 2019-07-05 at 8 55 02 am" src="https://user-images.githubusercontent.com/35712723/60689629-c2e43f00-9f02-11e9-8e1f-3e6112a1cd5c.png">

I tried using the `View Template` to display a `checkbox` in the column:
<img width="698" alt="Screen Shot 2019-07-05 at 8 52 38 am" src="https://user-images.githubusercontent.com/35712723/60689635-db545980-9f02-11e9-9482-82ab1c0fc30f.png">

I tried using an `If` element as well, but perhaps I didn't configure it correctly:
<img width="698" alt="Screen Shot 2019-07-05 at 8 54 28 am" src="https://user-images.githubusercontent.com/35712723/60689639-e3ac9480-9f02-11e9-92d6-2b79d5966556.png">
